spring.application.name=Sprintboot-app
spring.datasource.url=jdbc:postgresql://192.168.0.45:5432/yagnik_product_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional (debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true